### ISSUE TITLE
Ability to run from CLI?

### ISSUE THREAD

**Issue by uuacallis** [argilo/gr-elster#1]
So I use the raspberry pi from a remote headless console (without xwindows) 

curious if you have done any work for CLI based work?

**Comment by cameronswinoga** [comment]
The way I am doing it currently is taking the gnuradio companion generated python file (With GUI disabled in the options block) and then just running that in my headless server.

**Comment by argilo** [comment]
`apps/elster_rx_nogui.grc` should be suitable for use from the CLI.
