### ISSUE TITLE
rtlamr

### ISSUE THREAD

**Issue by gcormier** [argilo/gr-elster#4]
Nice work on this!

Have you seen the [RTLAMR ](https://github.com/bemasher/rtlamr) project? And confirmed it does not apply to the elster meters?

I'm hoping to gather electricity usage in Home Assistant. I found some [existing work done with RTLAMR](https://community.home-assistant.io/t/using-rtl-sdr-to-read-value-from-wireless-electric-gas-water-meters/52453), but I do have an Elster meter so perhaps I need to shift over to the work you've done.

Have you looked at reading any local gas or water meters?

**Comment by argilo** [comment]
Hi @gcormier, and thanks for your interest in the project.

I am familiar with the rtlamr project, and I've used it to listen in on my water meter: https://irrational.net/2019/03/26/tracking-down-a-water-leak/

The Elster electricity meters in my city use a completely different protocol called EnergyAxis 900 MHz LAN (EA_LAN), which gr-elster can partially decode.

As far as I know, the gas meters in my city are not wireless.

**Comment by gcormier** [comment]
Ok thanks. I've started up a thread here https://github.com/merbanan/rtl_433/issues/1196 to discuss bringing the work you've done into rtl_433!

I think you're right about gas, we can still submit manual readings online so they must gather them manually every few months.
