### ISSUE TITLE
More Info

### ISSUE THREAD

**Issue by gcormier** [argilo/gr-elster#5]
In reading the FCC filing I noticed this info which might be of interest to you/others.

![image](https://user-images.githubusercontent.com/8388983/71789666-63bece80-2ffa-11ea-9052-5fcc5ef744a6.png)

So it's merely rotating through each channel for each transmission.

**Comment by argilo** [comment]
Thanks for sharing that. It matches up with my observation that devices cycle through channels in a fixed order.

**Comment by gcormier** [comment]
Do you have an example GRC file you could share?

**Comment by argilo** [comment]
Sample GRC files are in the `apps` folder: https://github.com/argilo/gr-elster/tree/master/apps

**Comment by gcormier** [comment]
Thanks! I got it running now. I'm using the simpler elster_rx_multi.grc to see what it brings in. I ran the HackRF one converted slightly to run on my LimeSDR but it was outputting some weird values.
