### ISSUE TITLE
Not compatible

### ISSUE THREAD

**Issue by hc0r3n00b** [argilo/gr-elster#8]
Running into the following issue

CMake Error at CMakeLists.txt:88 (find_package):
  Could not find a configuration file for package "Gnuradio" that is
  compatible with requested version "3.9".

  The following configuration files were considered but not accepted:

    /usr/lib/x86_64-linux-gnu/cmake/gnuradio/GnuradioConfig.cmake, version: 3.8.1.0
    /lib/x86_64-linux-gnu/cmake/gnuradio/GnuradioConfig.cmake, version: 3.8.1.0

-- Configuring incomplete, errors occurred!
See also "/home/frodj/gr-elster/build/CMakeFiles/CMakeOutput.log".

**Comment by argilo** [comment]
As indicated in the error message, the latest version of gr-elster (on the master branch) requires GNU Radio 3.9 or later.

You'll either have to use a newer version of GNU Radio, or else check out the `maint-3.8` branch of gr-elster, which should be compatible with GNU Radio 3.8.
